[workspace]
members = ["contracts/global-registry", "contracts/lock-wrapper", "tests"]

[profile.release]
overflow-checks = true
strip = true
opt-level = 's'
lto = false
codegen-units = 1
panic = 'abort'
